### ISSUE TITLE
where are those images built?

### ISSUE THREAD

**Issue by FAIG2014** [VUnit/docker#1]
I am very new to Vunit.

I want to add an image to test modesim, in the main project's travis (https://github.com/VUnit/vunit)
I was going to add my dockerfile in the main repo, then I saw thise repo.

which bring me my questions:
* where are the dockerfiles for the 3 current images used the CI?
* where are they build? (I am guessing somebody has an account in dockerhub?)
* should I add my dockerfile here, or in the main repo?

**Comment by 1138-4EB** [comment]
> I want to add an image to test modesim, in the main project's travis (https://github.com/VUnit/vunit)

Although this is technically possible, and desirable, I'm afraid it is not legal. You/me/we are not allowed to distribute ModelSim. Publishing a docker image to a public registry is, in practice, distributing it. There are some alternatives:

- Publish a docker image which does not include ModelSim, but just the dependecies. Download and install ModelSim in each CI job/run.
- Publish a ready-to-use docker image to a private registry (which we don't have ATM) and use encrypted credentials in the CI jobs/runs.

I think that none of them is desirable in an open source project. If any vendor wants to support VUnit, an effort to facilitate CI of the main repo should be done. I am aware that the maintainers of this project are doing their best to get particular licensing conditions.

Meanwhile, it might be possible to run the tests in edaplayground (although I have never tried it).

>     * where are the dockerfiles for the 3 current images used the CI?

Since these images are based on images from ghdl/ghdl, the dockerfiles are very short, and they are inlined in `run.sh`:

- https://github.com/VUnit/docker/blob/master/run.sh#L13-L24
- https://github.com/VUnit/docker/blob/master/run.sh#L30-L41
- https://github.com/VUnit/docker/blob/master/run.sh#L47-L53

>     * where are they build? (I am guessing somebody has an account in dockerhub?)

The images are built in Travis CI and pushed to dockerhub. A 'bot' user is used for pushing, but the 'automated build' feature of dockerhub is not used.

See https://travis-ci.org/vunit/docker/builds

NOTE: I just saw that the builds are failing because of some changes I did on ghdl/docker a couple of weeks ago. I will fix it next week.

>     * should I add my dockerfile here, or in the main repo?

I think that it does not make much sense to add a Dockerfile neither to the main repo nor here. Hoewer, I think that it would be a very useful contribution to explain how to do it. This can be a blog post, a section/article in the docs/site, a page in the wiki... The article would include the stub of a dockerfile along with notes/hints about how to configure options for the unattended installation, how to add a license file or the envvars to connect to a license server, (optionally) how to install the license server in a sibling container, etc. Some useful references:

- https://github.com/1138-4EB/hwd-ide/wiki/Continuous-Integration-%28CI%29#propietary-applications-inside-a-docker-container, to install ModelSim/QuestaSim/Precision graphically.
- mviereck/x11docker and mviereck/runx, to run GUI apps inside docker containers on GNU/Linux or Windows 10.
- http://blog.reds.ch/?p=551, to generate a batch script graphically.

The most usual approach is to install ModelSim in a Debian/Ubuntu/Fedora container, then add Python and last VUnit. However, it is also possible not to install Python/VUnit in the same image, but have them installed on the host or in a sibling image/container instead:

- https://github.com/1138-4EB/vunit/commits/dockerexec-

**Comment by 1138-4EB** [comment]
> NOTE: I just saw that the builds are failing because of some changes I did on ghdl/docker a couple of weeks ago. I will fix it next week.

It is fixed now.
